from typing import Dict, NamedTuple, Optional
from BaseClasses import Location

class PacManWorld2Location(Location):
    game: str = "Pac-Man World 2"


class PacManWorld2LocationData(NamedTuple):
    location_id: int
    region: str
    is_boss: bool


OFFSET: int = 26022002000
location_table: Dict[str, PacManWorld2LocationData] = {}

# Much easier for me to keep track of location ids like this so I don't have to worry about counting.
def create_location(name: str, region: str, count: int = 1, is_boss: bool = False) -> None:
    for i in range(count):
        location_table[f"{region}: {name} #{i + 1}" if count > 1 else f"{region}: {name}"] = PacManWorld2LocationData(OFFSET + len(location_table), region, is_boss)

create_location("Cherry", "Pac-Village", 6)
create_location("Strawberry", "Pac-Village", 6)
create_location("Orange", "Pac-Village", 4)
create_location("Apple", "Pac-Village", 8)
create_location("Melon", "Pac-Village", 8)
create_location("Pac-Dot", "Pac-Village", 142)
create_location("Token", "Pac-Village", 8)
create_location("Bonus Token", "Pac-Village")
create_location("Level Complete", "Pac-Village")

create_location("Cherry", "The Bear Basics", 6)
create_location("Strawberry", "The Bear Basics", 6)
create_location("Orange", "The Bear Basics")
create_location("Apple", "The Bear Basics", 3)
create_location("Melon", "The Bear Basics", 2)
create_location("Pac-Dot", "The Bear Basics", 327)
create_location("Token", "The Bear Basics", 8)
create_location("Bonus Token", "The Bear Basics", 2)
create_location("Level Complete", "The Bear Basics")
create_location("Time Trial Complete", "The Bear Basics")

create_location("Cherry", "Canyon Chaos", 14)
create_location("Strawberry", "Canyon Chaos", 8)
create_location("Orange", "Canyon Chaos", 7)
create_location("Apple", "Canyon Chaos", 5)
create_location("Melon", "Canyon Chaos", 3)
create_location("Galaxian", "Canyon Chaos")
create_location("Pac-Dot", "Canyon Chaos", 178)
create_location("Token", "Canyon Chaos", 8)
create_location("Bonus Token", "Canyon Chaos", 2)
create_location("Level Complete", "Canyon Chaos")
create_location("Time Trial Complete", "Canyon Chaos")

create_location("Cherry", "Pac-Dot Pond", 9)
create_location("Strawberry", "Pac-Dot Pond", 7)
create_location("Orange", "Pac-Dot Pond", 9)
create_location("Apple", "Pac-Dot Pond", 9)
create_location("Melon", "Pac-Dot Pond", 5)
create_location("Galaxian", "Pac-Dot Pond")
create_location("Pac-Dot", "Pac-Dot Pond", 142)
create_location("Token", "Pac-Dot Pond", 8)
create_location("Bonus Token", "Pac-Dot Pond", 2)
create_location("Level Complete", "Pac-Dot Pond")
create_location("Time Trial Complete", "Pac-Dot Pond")

create_location("Defeat Blinky's Frog", "Blinky's Killer Frog", is_boss=True)

create_location("Cherry", "B-Doing Woods", 6)
create_location("Strawberry", "B-Doing Woods", 9)
create_location("Orange", "B-Doing Woods", 9)
create_location("Apple", "B-Doing Woods", 4)
create_location("Melon", "B-Doing Woods", 2)
create_location("Galaxian", "B-Doing Woods")
create_location("Pac-Dot", "B-Doing Woods", 217)
create_location("Token", "B-Doing Woods", 8)
create_location("Bonus Token", "B-Doing Woods", 2)
create_location("Level Complete", "B-Doing Woods")
create_location("Time Trial Complete", "B-Doing Woods")

create_location("Cherry", "Treewood Forest", 5)
create_location("Strawberry", "Treewood Forest", 6)
create_location("Orange", "Treewood Forest", 5)
create_location("Apple", "Treewood Forest", 4)
create_location("Melon", "Treewood Forest", 3)
create_location("Galaxian", "Treewood Forest")
create_location("Pac-Dot", "Treewood Forest", 194)
create_location("Token", "Treewood Forest", 8)
create_location("Bonus Token", "Treewood Forest", 2)
create_location("Level Complete", "Treewood Forest")
create_location("Time Trial Complete", "Treewood Forest")

create_location("Cherry", "Butane Pain", 5)
create_location("Strawberry", "Butane Pain", 4)
create_location("Orange", "Butane Pain", 8)
create_location("Apple", "Butane Pain", 2)
create_location("Melon", "Butane Pain", 2)
create_location("Galaxian", "Butane Pain")
create_location("Pac-Dot", "Butane Pain", 243)
create_location("Token", "Butane Pain", 8)
create_location("Bonus Token", "Butane Pain", 2)
create_location("Level Complete", "Butane Pain")
create_location("Time Trial Complete", "Butane Pain")

create_location("Defeat Inky's Saw", "Inky's Blade-o-Matic", is_boss=True)

create_location("Cherry", "Ice River Run", 6)
create_location("Strawberry", "Ice River Run", 11)
create_location("Orange", "Ice River Run", 2)
create_location("Apple", "Ice River Run", 8)
create_location("Galaxian", "Ice River Run")
create_location("Pac-Dot", "Ice River Run", 333)
create_location("Token", "Ice River Run", 8)
create_location("Bonus Token", "Ice River Run", 2)
create_location("Level Complete", "Ice River Run")
create_location("Time Trial Complete", "Ice River Run")

create_location("Cherry", "Avalanche Alley", 24)
create_location("Strawberry", "Avalanche Alley", 33)
create_location("Apple", "Avalanche Alley", 36)
create_location("Melon", "Avalanche Alley", 4)
create_location("Galaxian", "Avalanche Alley")
create_location("Pac-Dot", "Avalanche Alley", 297)
create_location("Token", "Avalanche Alley", 8)
create_location("Bonus Token", "Avalanche Alley", 2)
create_location("Level Complete", "Avalanche Alley")
create_location("Time Trial Complete", "Avalanche Alley")

create_location("Cherry", "Blade Mountain", 22)
create_location("Strawberry", "Blade Mountain", 23)
create_location("Orange", "Blade Mountain")
create_location("Apple", "Blade Mountain", 7)
create_location("Melon", "Blade Mountain")
create_location("Galaxian", "Blade Mountain")
create_location("Pac-Dot", "Blade Mountain", 216)
create_location("Token", "Blade Mountain", 8)
create_location("Bonus Token", "Blade Mountain", 2)
create_location("Level Complete", "Blade Mountain")
create_location("Time Trial Complete", "Blade Mountain")

create_location("Defeat Pinky's Blower", "Pinky's Revenge", is_boss=True)

create_location("Cherry", "Into the Volcano", 3)
create_location("Strawberry", "Into the Volcano", 2)
create_location("Orange", "Into the Volcano", 2)
create_location("Apple", "Into the Volcano", 3)
create_location("Melon", "Into the Volcano")
create_location("Galaxian", "Into the Volcano")
create_location("Pac-Dot", "Into the Volcano", 200)
create_location("Token", "Into the Volcano", 8)
create_location("Bonus Token", "Into the Volcano", 2)
create_location("Level Complete", "Into the Volcano")
create_location("Time Trial Complete", "Into the Volcano")

create_location("Cherry", "Volcanic Panic", 4)
create_location("Strawberry", "Volcanic Panic", 6)
create_location("Orange", "Volcanic Panic", 2)
create_location("Apple", "Volcanic Panic", 5)
create_location("Melon", "Volcanic Panic", 3)
create_location("Galaxian", "Volcanic Panic")
create_location("Pac-Dot", "Volcanic Panic", 310)
create_location("Token", "Volcanic Panic", 8)
create_location("Bonus Token", "Volcanic Panic", 2)
create_location("Level Complete", "Volcanic Panic")
create_location("Time Trial Complete", "Volcanic Panic")

create_location("Cherry", "Magma Opus", 5)
create_location("Orange", "Magma Opus", 5)
create_location("Apple", "Magma Opus", 4)
create_location("Melon", "Magma Opus", 2)
create_location("Galaxian", "Magma Opus")
create_location("Pac-Dot", "Magma Opus", 226)
create_location("Token", "Magma Opus", 8)
create_location("Bonus Token", "Magma Opus", 2)
create_location("Level Complete", "Magma Opus")
create_location("Time Trial Complete", "Magma Opus")

create_location("Defeat Clyde's Machine", "Clyde in the Caldera", is_boss=True)

create_location("Cherry", "Scuba Duba", 7)
create_location("Strawberry", "Scuba Duba", 8)
create_location("Orange", "Scuba Duba", 4)
create_location("Apple", "Scuba Duba", 4)
create_location("Melon", "Scuba Duba", 6)
create_location("Galaxian", "Scuba Duba")
create_location("Pac-Dot", "Scuba Duba", 133)
create_location("Token", "Scuba Duba", 8)
create_location("Bonus Token", "Scuba Duba", 2)
create_location("Level Complete", "Scuba Duba")
create_location("Time Trial Complete", "Scuba Duba")

create_location("Cherry", "Shark Attack", 10)
create_location("Strawberry", "Shark Attack", 7)
create_location("Orange", "Shark Attack", 5)
create_location("Apple", "Shark Attack", 5)
create_location("Melon", "Shark Attack", 3)
create_location("Galaxian", "Shark Attack")
create_location("Pac-Dot", "Shark Attack", 111)
create_location("Token", "Shark Attack", 8)
create_location("Bonus Token", "Shark Attack", 2)
create_location("Level Complete", "Shark Attack")
create_location("Time Trial Complete", "Shark Attack")

create_location("Cherry", "Yellow Pac-Marine", 20)
create_location("Orange", "Yellow Pac-Marine", 5)
create_location("Apple", "Yellow Pac-Marine", 2)
create_location("Token", "Yellow Pac-Marine", 8)
create_location("Bonus Token", "Yellow Pac-Marine", 2)
create_location("Level Complete", "Yellow Pac-Marine")
create_location("Time Trial Complete", "Yellow Pac-Marine")

create_location("Defeat Megawhale", "Whale on a Sub", is_boss=True)

create_location("Cherry", "Haunted Boardwalk", 13)
create_location("Strawberry", "Haunted Boardwalk", 4)
create_location("Orange", "Haunted Boardwalk", 6)
create_location("Apple", "Haunted Boardwalk", 8)
create_location("Melon", "Haunted Boardwalk", 9)
create_location("Galaxian", "Haunted Boardwalk")
create_location("Pac-Dot", "Haunted Boardwalk", 153)
create_location("Token", "Haunted Boardwalk", 8)
create_location("Bonus Token", "Haunted Boardwalk", 2)
create_location("Level Complete", "Haunted Boardwalk")
create_location("Time Trial Complete", "Haunted Boardwalk")

create_location("Cherry", "Night Crawling", 2)
create_location("Strawberry", "Night Crawling")
create_location("Orange", "Night Crawling")
create_location("Apple", "Night Crawling", 4)
create_location("Melon", "Night Crawling", 2)
create_location("Pac-Dot", "Night Crawling", 255)
create_location("Token", "Night Crawling", 8)
create_location("Bonus Token", "Night Crawling", 2)
create_location("Level Complete", "Night Crawling")
create_location("Time Trial Complete", "Night Crawling")

create_location("Cherry", "Ghost Bayou", 12)
create_location("Strawberry", "Ghost Bayou", 21)
create_location("Apple", "Ghost Bayou", 13)
create_location("Melon", "Ghost Bayou", 13)
create_location("Galaxian", "Ghost Bayou")
create_location("Pac-Dot", "Ghost Bayou", 535)
create_location("Token", "Ghost Bayou", 8)
create_location("Bonus Token", "Ghost Bayou", 2)
create_location("Level Complete", "Ghost Bayou")
create_location("Time Trial Complete", "Ghost Bayou")

create_location("Defeat Spooky", "Spooky", is_boss=True)